"""Add title column in Sheet table

Revision ID: 11cdb907390d
Revises: f983ecb26447
Create Date: 2024-09-02 21:37:22.331599

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "11cdb907390d"
down_revision: Union[str, None] = "f983ecb26447"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sheets", sa.Column("title", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sheets", "title")
    # ### end Alembic commands ###
