"""delete posts table and update vk_activities table

Revision ID: 1b1b43fa6eba
Revises: 759a3e94362b
Create Date: 2024-07-24 12:56:47.835808

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1b1b43fa6eba"
down_revision: Union[str, None] = "759a3e94362b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP TABLE posts CASCADE')
    op.add_column(
        "vk_activities", sa.Column("post_url", sa.String(), nullable=False)
    )
    op.execute('ALTER TYPE activity_type RENAME TO activitytype')

    op.drop_column("vk_activities", "post_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "vk_activities",
        sa.Column(
            "post_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.create_foreign_key(
        "vk_activities_post_id_fkey",
        "vk_activities",
        "posts",
        ["post_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.alter_column(
        "vk_activities",
        "activity",
        existing_type=sa.Enum("VK_LIKE", "VK_COMMENT", name="activitytype"),
        type_=postgresql.ENUM("VK_LIKE", "VK_COMMENT", name="activity_type"),
        existing_nullable=False,
    )
    op.drop_column("vk_activities", "post_url")
    op.create_table(
        "posts",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("url", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="posts_pkey"),
        sa.UniqueConstraint("url", name="posts_url_key"),
    )
    # ### end Alembic commands ###
