"""Add EventType model

Revision ID: 1c5c4cf57921
Revises: 053df824c428
Create Date: 2024-09-21 17:15:07.363347

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1c5c4cf57921"
down_revision: Union[str, None] = "053df824c428"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "event_types",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("points", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(
        op.f("ix_event_types_id"), "event_types", ["id"], unique=False
    )
    op.add_column(
        "event_registration_tables",
        sa.Column("event_type_id", sa.Integer(), nullable=False),
    )
    op.create_foreign_key(
        None,
        "event_registration_tables",
        "event_types",
        ["event_type_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "event_registration_tables", type_="foreignkey")
    op.drop_column("event_registration_tables", "event_type_id")
    op.drop_index(op.f("ix_event_types_id"), table_name="event_types")
    op.drop_table("event_types")
    # ### end Alembic commands ###
