"""Add unique constraint in protocol_person table

Revision ID: 43ba85b957f1
Revises: a92953001354
Create Date: 2024-08-15 20:16:03.679638

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "43ba85b957f1"
down_revision: Union[str, None] = "a92953001354"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "_protocol_matched_person_uc",
        "protocol_persons",
        ["protocol_id", "matched_person_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "_protocol_matched_person_uc", "protocol_persons", type_="unique"
    )
    # ### end Alembic commands ###
