"""Rename 'activity' to 'activity_type' in VkActivity table

Revision ID: 7174752ae72c
Revises: 1c5c4cf57921
Create Date: 2024-09-25 18:18:14.430849

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7174752ae72c"
down_revision: Union[str, None] = "1c5c4cf57921"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "vk_activities",
        sa.Column(
            "activity_type",
            sa.Enum("VK_LIKE", "VK_COMMENT", name="activitytype"),
            nullable=False,
        ),
    )
    op.drop_column("vk_activities", "activity")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "vk_activities",
        sa.Column(
            "activity",
            postgresql.ENUM("VK_LIKE", "VK_COMMENT", name="activitytype"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("vk_activities", "activity_type")
    # ### end Alembic commands ###
