"""Detele filled column in Protocol

Revision ID: 74dbfd7dbbaa
Revises: 11cdb907390d
Create Date: 2024-09-05 15:37:12.980472

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "74dbfd7dbbaa"
down_revision: Union[str, None] = "11cdb907390d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("protocols", "filled")
    op.add_column(
        "sheets", sa.Column("table_url", sa.Integer(), nullable=False)
    )
    op.drop_constraint("sheets_sheet_id_key", "sheets", type_="unique")
    op.create_unique_constraint(None, "sheets", ["table_url"])
    op.drop_column("sheets", "sheet_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sheets",
        sa.Column(
            "sheet_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(None, "sheets", type_="unique")
    op.create_unique_constraint("sheets_sheet_id_key", "sheets", ["sheet_id"])
    op.drop_column("sheets", "table_url")
    op.add_column(
        "protocols",
        sa.Column("filled", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
