"""Add unique constraint in VkActivity

Revision ID: 93862d9044cc
Revises: 27eff2af5234
Create Date: 2024-09-27 13:02:43.958052

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "93862d9044cc"
down_revision: Union[str, None] = "27eff2af5234"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "_person_post_activity_uc",
        "vk_activities",
        ["person_id", "post_url", "activity_type"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "_person_post_activity_uc", "vk_activities", type_="unique"
    )
    # ### end Alembic commands ###
