"""Delete event_type attribute in EventTable model

Revision ID: a16b45d4000c
Revises: 57f70da9c4be
Create Date: 2024-09-18 18:20:56.071819

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a16b45d4000c"
down_revision: Union[str, None] = "57f70da9c4be"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("event_registration_tables", "event_type")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "event_registration_tables",
        sa.Column(
            "event_type",
            postgresql.ENUM(
                "PRO_WEEKEND",
                "COMMITTEE_EVENT_GUSS",
                "COMMITTEE_EVENT_CITY",
                "SOVIET_EVENT",
                "OON_EVENT",
                "PO_EVENT",
                name="eventtype",
            ),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
