"""Rename tables, add 'protocol_persons' table, edit 'protocols' table

Revision ID: a7d70bd4dd5e
Revises: aea0f4e22fd3
Create Date: 2024-08-03 14:56:45.913005

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a7d70bd4dd5e"
down_revision: Union[str, None] = "aea0f4e22fd3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE committee_membership RENAME TO memberships")
    op.create_table(
        "protocol_persons",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("last_name", sa.String(), nullable=False),
        sa.Column("matched_person_id", sa.Integer(), nullable=True),
        sa.Column("points_added", sa.Boolean(), nullable=False),
        sa.Column("protocol_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["matched_person_id"], ["persons.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["protocol_id"], ["protocols.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "protocols", sa.Column("date", sa.DateTime(), nullable=False)
    )
    op.drop_column("protocols", "content")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "protocols",
        sa.Column(
            "content",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("protocols", "date")
    op.create_table(
        "committee_membership",
        sa.Column(
            "person_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "committee_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["committee_id"],
            ["committees.id"],
            name="committee_membership_committee_id_fkey",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["persons.id"],
            name="committee_membership_person_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "person_id", "committee_id", name="committee_membership_pkey"
        ),
    )
    op.drop_table("protocol_persons")
    op.drop_table("membership")
    # ### end Alembic commands ###
