"""Add 'filled' column in protocols

Revision ID: a92953001354
Revises: e25f35208d35
Create Date: 2024-08-15 19:43:23.873015

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a92953001354"
down_revision: Union[str, None] = "e25f35208d35"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "committees", ["talisman"])
    op.create_unique_constraint(None, "committees", ["protocols_document_id"])
    op.add_column(
        "protocols", sa.Column("filled", sa.Boolean(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("protocols", "filled")
    op.drop_constraint(None, "committees", type_="unique")
    op.drop_constraint(None, "committees", type_="unique")
    # ### end Alembic commands ###
