"""Add indexes and update some tables

Revision ID: c0b2b7eccd87
Revises: dedecdb24e95
Create Date: 2024-08-10 11:30:16.652696

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c0b2b7eccd87"
down_revision: Union[str, None] = "dedecdb24e95"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "audit_logs", sa.Column("person_id", sa.Integer(), nullable=True)
    )
    op.create_index(
        op.f("ix_audit_logs_id"), "audit_logs", ["id"], unique=False
    )
    op.create_foreign_key(
        None,
        "audit_logs",
        "persons",
        ["person_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("audit_logs", "table_name")
    op.create_index(
        op.f("ix_categories_id"), "categories", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_committees_id"), "committees", ["id"], unique=False
    )
    op.create_index(op.f("ix_persons_id"), "persons", ["id"], unique=False)
    op.create_index(
        op.f("ix_protocol_persons_id"),
        "protocol_persons",
        ["id"],
        unique=False,
    )
    op.create_index(op.f("ix_protocols_id"), "protocols", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_protocols_id"), table_name="protocols")
    op.drop_index(
        op.f("ix_protocol_persons_id"), table_name="protocol_persons"
    )
    op.drop_index(op.f("ix_persons_id"), table_name="persons")
    op.drop_index(op.f("ix_committees_id"), table_name="committees")
    op.drop_index(op.f("ix_categories_id"), table_name="categories")
    op.add_column(
        "audit_logs",
        sa.Column(
            "table_name", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(None, "audit_logs", type_="foreignkey")
    op.drop_index(op.f("ix_audit_logs_id"), table_name="audit_logs")
    op.drop_column("audit_logs", "person_id")
    # ### end Alembic commands ###
