"""Add unique constaints 2

Revision ID: f95125977ebe
Revises: 89a395e6f508
Create Date: 2024-08-03 20:27:18.270608

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f95125977ebe"
down_revision: Union[str, None] = "89a395e6f508"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "_number_date_committee_uc",
        "protocols",
        ["number", "date", "committee_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "_number_date_committee_uc", "protocols", type_="unique"
    )
    # ### end Alembic commands ###
