version: '3.9'
services:
  db:
    image: postgres:16-alpine
    env_file:
      - ./.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: on-failure
    ports:
      - '5432:5432'
  bot:
    build: .
    command: sh -c "until pg_isready -h db -p 5432; do sleep 1; done && alembic upgrade head && python -m src.main"
    env_file:
      - ./.env
    depends_on:
      - db
    restart: always
  vk_activities_checker:
    build: .
    command: sh -c "until pg_isready -h db -p 5432; do sleep 1; done && python -m src.vk_activities_checker"
    env_file:
      - ./.env
    depends_on:
      - db
    restart: always

volumes:
  pgdata: