"""Add 'event_type' in EventTable model

Revision ID: 053df824c428
Revises: c0664396e2cf
Create Date: 2024-09-21 13:54:01.266730

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "053df824c428"
down_revision: Union[str, None] = "c0664396e2cf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "event_registration_tables",
        sa.Column(
            "event_type",
            sa.Enum(
                "PRO_WEEKEND",
                "COMMITTEE_EVENT_GUSS",
                "COMMITTEE_EVENT_CITY",
                "SOVIET_EVENT",
                "OON_EVENT",
                "PO_EVENT",
                name="eventtype",
            ),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("event_registration_tables", "event_type")
    # ### end Alembic commands ###
