"""Edit ProtocolPerson table

Revision ID: 0e9fe120bb1e
Revises: 74dbfd7dbbaa
Create Date: 2024-09-05 18:14:03.588204

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0e9fe120bb1e"
down_revision: Union[str, None] = "74dbfd7dbbaa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "protocol_persons", sa.Column("full_name", sa.String(), nullable=False)
    )
    op.drop_constraint(
        "_first_last_protocol_uc", "protocol_persons", type_="unique"
    )
    op.create_unique_constraint(
        "_first_last_protocol_uc",
        "protocol_persons",
        ["full_name", "protocol_id"],
    )
    op.drop_column("protocol_persons", "last_name")
    op.drop_column("protocol_persons", "first_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "protocol_persons",
        sa.Column(
            "first_name", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "protocol_persons",
        sa.Column(
            "last_name", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(
        "_first_last_protocol_uc", "protocol_persons", type_="unique"
    )
    op.create_unique_constraint(
        "_first_last_protocol_uc",
        "protocol_persons",
        ["first_name", "last_name", "protocol_id"],
    )
    op.drop_column("protocol_persons", "full_name")
    # ### end Alembic commands ###
