"""Rename 'action' column to 'action_type'

Revision ID: 7e6c70a9371e
Revises: c0b2b7eccd87
Create Date: 2024-08-10 11:41:04.755382

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7e6c70a9371e"
down_revision: Union[str, None] = "c0b2b7eccd87"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "audit_logs",
        sa.Column(
            "action_type",
            sa.Enum(
                "INSERT_PERSON",
                "DELETE_PERSON",
                "INSERT_MEMBERSHIP",
                "UPDATE_MEMBERSHIP",
                "DELETE_MEMBERSHIP",
                "UPDATE_PERSON_POINTS",
                "UPDATE_PERSON_FIRST_NAME",
                "UPDATE_PERSON_LAST_NAME",
                name="actiontype",
            ),
            nullable=False,
        ),
    )
    op.drop_column("audit_logs", "action")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "audit_logs",
        sa.Column(
            "action",
            postgresql.ENUM(
                "INSERT_PERSON",
                "DELETE_PERSON",
                "INSERT_MEMBERSHIP",
                "UPDATE_MEMBERSHIP",
                "DELETE_MEMBERSHIP",
                "INSERT_VK_ACTIVITY",
                "UPDATE_PERSON_POINTS",
                name="actiontype",
            ),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("audit_logs", "action_type")
    # ### end Alembic commands ###
