"""Remove CASCADE deliting in 'person_id' column in audit_logs table

Revision ID: c44b7f3d68b6
Revises: 2b0a60d48ced
Create Date: 2024-08-13 20:01:58.043305

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c44b7f3d68b6"
down_revision: Union[str, None] = "2b0a60d48ced"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "audit_logs_person_id_fkey", "audit_logs", type_="foreignkey"
    )
    op.create_foreign_key(None, "audit_logs", "persons", ["person_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "audit_logs", type_="foreignkey")
    op.create_foreign_key(
        "audit_logs_person_id_fkey",
        "audit_logs",
        "persons",
        ["person_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
