"""Add Protocol model

Revision ID: d710e999260e
Revises: 1b1b43fa6eba
Create Date: 2024-08-02 11:36:45.122998

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d710e999260e"
down_revision: Union[str, None] = "1b1b43fa6eba"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "protocols",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("content", sa.JSON(), nullable=False),
        sa.Column("committee_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["committee_id"], ["committees.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "audit_logs",
        sa.Column(
            "action",
            sa.Enum(
                "INSERT_PERSON",
                "DELETE_PERSON",
                "INSERT_MEMBERSHIP",
                "UPDATE_MEMBERSHIP",
                "DELETE_MEMBERSHIP",
                "UPDATE_PERSON_POINTS",
                name="actiontype",
            ),
            nullable=False,
        ),
    )
    op.drop_column("audit_logs", "action_type")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "audit_logs",
        sa.Column(
            "action_type",
            postgresql.ENUM(
                "INSERT_PERSON",
                "DELETE_PERSON",
                "INSERT_MEMBERSHIP",
                "UPDATE_MEMBERSHIP",
                "DELETE_MEMBERSHIP",
                "INSERT_VK_ACTIVITY",
                "UPDATE_PERSON_POINTS",
                name="actiontype",
            ),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("audit_logs", "action")
    op.drop_table("protocols")
    # ### end Alembic commands ###
