"""add committee talismans

Revision ID: db1027b969f4
Revises: d2dea8080d2a
Create Date: 2024-07-21 10:48:17.519011

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "db1027b969f4"
down_revision: Union[str, None] = "d2dea8080d2a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "committees", sa.Column("talisman", sa.Text(), nullable=True)
    )
    op.execute("UPDATE committees SET talisman = '🐻' WHERE name = 'КЛЮКВА'")
    op.execute("UPDATE committees SET talisman = '🐸' WHERE name = 'КДК'")
    op.execute("UPDATE committees SET talisman = '🐭' WHERE name = 'КОТ'")
    op.execute("UPDATE committees SET talisman = '🦆' WHERE name = 'ИЦ'")
    op.execute("UPDATE committees SET talisman = '🦄' WHERE name = 'ЦВК'")
    op.execute("UPDATE committees SET talisman = '🦔' WHERE name = 'СПОК'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("committees", "talisman")
    # ### end Alembic commands ###
