"""Remove CASCADE deliting in 'person_id' column in audit_logs table 2

Revision ID: e25f35208d35
Revises: c44b7f3d68b6
Create Date: 2024-08-13 20:06:59.076555

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e25f35208d35"
down_revision: Union[str, None] = "c44b7f3d68b6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "audit_logs_person_id_fkey", "audit_logs", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "audit_logs",
        "persons",
        ["person_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "audit_logs", type_="foreignkey")
    op.create_foreign_key(
        "audit_logs_person_id_fkey",
        "audit_logs",
        "persons",
        ["person_id"],
        ["id"],
    )
    # ### end Alembic commands ###
