"""empty message

Revision ID: ebce757ff84c
Revises: 0e9fe120bb1e
Create Date: 2024-09-14 21:04:04.430952

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ebce757ff84c"
down_revision: Union[str, None] = "0e9fe120bb1e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "protocol_persons_matched_person_id_fkey",
        "protocol_persons",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "protocol_persons",
        "persons",
        ["matched_person_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "protocol_persons", type_="foreignkey")
    op.create_foreign_key(
        "protocol_persons_matched_person_id_fkey",
        "protocol_persons",
        "persons",
        ["matched_person_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
