"""Add Sheet and SheetPerson tables

Revision ID: f983ecb26447
Revises: 43ba85b957f1
Create Date: 2024-09-02 20:36:26.787634

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f983ecb26447"
down_revision: Union[str, None] = "43ba85b957f1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sheets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sheet_id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sheet_id"),
    )
    op.create_index(op.f("ix_sheets_id"), "sheets", ["id"], unique=False)
    op.create_table(
        "sheet_persons",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("last_name", sa.String(), nullable=False),
        sa.Column("matched_person_id", sa.Integer(), nullable=True),
        sa.Column("points_added", sa.Boolean(), nullable=False),
        sa.Column("sheet_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["matched_person_id"], ["persons.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["sheet_id"], ["sheets.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "first_name", "last_name", "sheet_id", name="_first_last_sheet_uc"
        ),
        sa.UniqueConstraint(
            "sheet_id", "matched_person_id", name="_sheet_matched_person_uc"
        ),
    )
    op.create_index(
        op.f("ix_sheet_persons_id"), "sheet_persons", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_sheet_persons_sheet_id"),
        "sheet_persons",
        ["sheet_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_protocol_persons_protocol_id"),
        "protocol_persons",
        ["protocol_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_protocol_persons_protocol_id"), table_name="protocol_persons"
    )
    op.drop_index(
        op.f("ix_sheet_persons_sheet_id"), table_name="sheet_persons"
    )
    op.drop_index(op.f("ix_sheet_persons_id"), table_name="sheet_persons")
    op.drop_table("sheet_persons")
    op.drop_index(op.f("ix_sheets_id"), table_name="sheets")
    op.drop_table("sheets")
    # ### end Alembic commands ###
